import type { Metadata } from "next";
import type { ReactNode } from "react";
import "./globals.css";

type Props = Readonly<{
  children: ReactNode;
}>;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default ({ children }: Props) => {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
};
