name: 'Build application'
description: 'Build the application and upload artifacts'

inputs:
  upload-artifacts:
    description: 'Whether to upload build artifacts'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Build application
      run: pnpm run build
      shell: bash

    - name: Upload build artifacts
      if: inputs.upload-artifacts == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: next-build
        path: apps/app/.next
        retention-days: 1
